#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir log
touch combustor2D_RF.foam
rm -r 0
cp -r 0.bak 0

runApplication blockMesh  
runApplication checkMesh
runApplication renumberMesh -overwrite

runApplication mapFields ../initialConditions/ -case . -parallelSource -sourceTime latestTime

runApplication decomposePar
runParallel reactingFoam

mv ./log.* ./log

# ----------------------------------------------------------------- end-of-file
