#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

setDecompMethod(){ \
    foamDictionary -entry "method" -set $1 system/decomposeParDict;
}

#- set local valriables
runApplication surfaceTransformPoints -scale "(1e-3 1e-3 1e-3)" \
               constant/triSurface/combustor_mm.stl \
               constant/triSurface/combustor.stl

runApplication blockMesh

runApplication surfaceFeatures

if [ -n "$1" ] && [ "$1" -gt 1 ]; then

    foamDictionary -entry "numberOfSubdomains" -set "$1" system/decomposeParDict;

    setDecompMethod scotch;
       
    runApplication decomposePar

    setDecompMethod ptscotch;
    
    runParallel snappyHexMesh
else
    runApplication snappyHexMesh
fi

# end-of-file
