#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir log
touch initialConditionsRF.foam

runApplication blockMesh  
runApplication checkMesh
runApplication renumberMesh -overwrite

runApplication decomposePar
runParallel reactingFoam

mv ./log.* ./log

# ----------------------------------------------------------------- end-of-file
