#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir log
touch combustor2D_spray.foam

runApplication blockMesh  
runApplication checkMesh
runApplication renumberMesh -overwrite

runApplication mapFields ../../lab4/combustor2D_RPF/ -case . -parallelSource -sourceTime latestTime

runApplication chemkinToFoam \
	       chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
	       constant/reactions constant/speciesThermo

runApplication decomposePar
runParallel sprayFoam

mv ./log.* ./log

# ----------------------------------------------------------------- end-of-file
