#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.bak 0

runApplication blockMesh
runApplication mapFields ../../Lab04-heatTransfer/combustor2D_RPF/ -case . -sourceTime latestTime

runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
               constant/reactions constant/speciesThermo

runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
