#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy motorbike surface from resources directory
runApplication surfaceFeatureExtract

runApplication blockMesh


#- -------------
if [ -n "$1" ] && [ "$1" -gt 1 ]; then

    foamDictionary -disableFunctionEntries \
                   -entry "numberOfSubdomains" -set "$1" system/decomposeParDict;

    setDecompMethod scotch;
       
    runApplication decomposePar

    setDecompMethod ptscotch;
    
    runParallel snappyHexMesh -overwrite

    #- For parallel running
    ls -d processor* | xargs -I {} rm -rf ./{}/0
    ls -d processor* | xargs -I {} cp -r 0.org ./{}/0

    runParallel patchSummary

    runApplication reconstructParMesh -constant
    runApplication reconstructPar -latestTime
    
else
    #- For non-parallel running
    cp -r 0.org 0 > /dev/null 2>&1

    runApplication snappyHexMesh -overwrite
fi




# ----------------------------------------------------------------- end-of-file
