#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create thermo to work with lagrangian
runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
               constant/reactions constant/speciesThermo

# paraFoam -touchAll
touch combustor2D-wf{wallFilm}.OpenFOAM
touch combustor2D-wf.OpenFOAM
touch combustor2D-wf.blockMesh


runApplication $(getApplication)

# ----------------------------------------------------------------- end-of-file
