#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir log
touch initialConditions.foam

runApplication blockMesh  
runApplication checkMesh
runApplication renumberMesh -overwrite

runApplication chemkinToFoam \
	       chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
	       constant/reactions constant/thermo.mixture # these files must be modified accordingly to methane reaaction

runApplication decomposePar
runParallel reactingFoam

mv ./log.* ./log

# ----------------------------------------------------------------- end-of-file
