#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#- set local valriables
runApplication surfaceTransformPoints -scale "(1e-3 1e-3 1e-3)" \
               constant/triSurface/combustor_mm.stl \
               constant/triSurface/combustor.stl

runApplication blockMesh

runApplication checkMesh

runApplication surfaceFeatures

runApplication decomposePar

runParallel snappyHexMesh

runApplication checkMesh

# end-of-file
