#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

. ${WM_PROJECT_DIR}/bin/tools/CleanFunctions

cleanCase

rm -r initialConditions-cmb.tar.gz 2>/dev/null
rm -r 0 2>/dev/null
rm -rf constant/polyMesh 2>/dev/null
rm -r postProcessing 2>/dev/null
rm -r processor* 2>/dev/null
rm -r log* 2>/dev/null
