#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp ../initialConditions-cmb.tar.gz .
tar zxf initialConditions-cmb.tar.gz
mv initialConditions 0

runApplication blockMesh
runApplication reactingFoam

# ----------------------------------------------------------------- end-of-file
